name: SCP files From Actions To EC2
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps: 
      - name: From Github Actions to AWS EC2 through SCP
        uses: appleboy/scp-action@v0.1.7
        with: 
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: ActionsController.java
          target: /home/ubuntu/app-with-actions/src/main/java/actions/controller
